"""
Writer Agent - Specialist for synthesizing and writing content.

This agent is called when the orchestrator needs to create written content,
summarize information, or format output for users.

Example tasks:
    - "Write a summary of the research findings"
    - "Create a report from the analysis"
    - "Format the results as a professional document"
"""

from inspect import cleandoc

from schemas import AgentProfile
from .base_specialist import BaseSpecialist


# default profile for writer specialist
WRITER_PROFILE = AgentProfile(
    name="writer_agent",
    role="Writing Specialist",
    capabilities=[
        "content creation",
        "summarization",
        "report writing",
        "formatting",
        "synthesis",
    ],
    system_prompt=cleandoc("""
        You are a writing specialist. Your job is to:
        1. Create clear, well-structured content
        2. Synthesize information from multiple sources
        3. Adapt tone and style to the audience
        4. Ensure accuracy and readability

        Write concisely but completely. Use formatting to enhance clarity.
    """).strip(),
)


class WriterAgent(BaseSpecialist):
    """
    Specialist agent for writing and content synthesis.

    In mock mode, returns simulated written content.
    In real mode, would use LLM to generate polished content.

    Usage:
        agent = WriterAgent()
        result = agent.execute(task="write a summary of the findings")
    """

    def __init__(
        self,
        profile: AgentProfile | None = None,
        use_mock: bool = True,
        verbose: bool = True,
    ):
        super().__init__(
            profile=profile or WRITER_PROFILE,
            use_mock=use_mock,
            verbose=verbose,
        )

    def _execute_mock(self, task: str) -> str:
        """
        Return mock written content.

        Generates realistic but fake written output based on the task.
        """
        task_lower = task.lower()

        if "summar" in task_lower:
            return cleandoc("""
                # Executive Summary

                ## Overview
                This document summarizes the key findings from our investigation. The analysis reveals several important insights that will inform our next steps.

                ## Key Points

                1. **Primary Finding**: The data supports moving forward with the proposed approach, with some modifications to address identified risks.

                2. **Supporting Evidence**: Multiple data sources confirm the viability of this direction, with a confidence level of 85%.

                3. **Recommendations**:
                   - Proceed with Phase 1 implementation
                   - Monitor key metrics weekly
                   - Reassess after 30 days

                ## Conclusion
                The evidence strongly suggests that the proposed strategy will achieve the desired outcomes. We recommend approval to proceed.

                ---
                *Summary prepared by Writing Specialist*
            """).strip()

        elif "report" in task_lower:
            return cleandoc("""
                # Comprehensive Report

                ## 1. Introduction
                This report presents a detailed analysis of the subject matter, incorporating research findings and expert analysis.

                ## 2. Background
                The topic under investigation has significant implications for stakeholders. This report aims to provide actionable insights.

                ## 3. Methodology
                - Data collection from multiple sources
                - Quantitative and qualitative analysis
                - Expert review and validation

                ## 4. Findings

                ### 4.1 Key Discovery
                The primary finding indicates a positive trajectory with manageable risks.

                ### 4.2 Supporting Data
                | Metric | Value | Status |
                |--------|-------|--------|
                | Progress | 75% | On Track |
                | Quality | High | Exceeds |
                | Timeline | +5 days | Acceptable |

                ## 5. Recommendations
                1. Continue current approach
                2. Allocate additional resources to critical path
                3. Schedule follow-up review

                ## 6. Conclusion
                The analysis supports a favorable outlook. Recommended actions should be implemented within the specified timeline.

                ---
                *Report generated by Writing Specialist*
            """).strip()

        elif "email" in task_lower or "message" in task_lower:
            return cleandoc("""
                Subject: Summary of Findings and Next Steps

                Dear Team,

                I hope this message finds you well. I'm writing to share the key outcomes from our recent analysis.

                **Summary:**
                Our investigation has yielded positive results. The main findings indicate that we're on track to meet our objectives.

                **Key Points:**
                • The data supports our current strategy
                • Minor adjustments recommended in two areas
                • Timeline remains achievable with existing resources

                **Next Steps:**
                1. Review attached detailed analysis
                2. Provide feedback by Friday
                3. Join the follow-up meeting next Tuesday

                Please let me know if you have any questions or need additional information.

                Best regards,
                Writing Specialist
            """).strip()

        elif "format" in task_lower or "present" in task_lower:
            return cleandoc("""
                ═══════════════════════════════════════════════════════════
                                    FORMATTED PRESENTATION
                ═══════════════════════════════════════════════════════════

                ┌─────────────────────────────────────────────────────────┐
                │                    KEY HIGHLIGHTS                       │
                ├─────────────────────────────────────────────────────────┤
                │  ✓ Objective achieved                                   │
                │  ✓ Quality standards met                                │
                │  ✓ Timeline on schedule                                 │
                │  ⚠ Minor issues identified (addressed in plan)          │
                └─────────────────────────────────────────────────────────┘

                DETAILED BREAKDOWN:
                -------------------
                → Phase 1: Complete ████████████ 100%
                → Phase 2: In Progress ████████░░ 80%
                → Phase 3: Pending ░░░░░░░░░░░░ 0%

                RECOMMENDATIONS:
                -------------------
                1. Approve Phase 2 completion
                2. Initiate Phase 3 planning
                3. Allocate resources accordingly

                ═══════════════════════════════════════════════════════════
                                    END OF PRESENTATION
                ═══════════════════════════════════════════════════════════
            """).strip()

        else:
            topic = task.replace("write", "").replace("create", "").strip()
            return cleandoc(f"""
                # {topic.title()}

                ## Overview
                This document addresses the requested topic with comprehensive coverage and clear organization.

                ## Main Content

                The subject matter has been carefully considered and structured for clarity. Key aspects include:

                1. **Foundation**: Understanding the core concepts
                2. **Analysis**: Examining the relevant factors
                3. **Synthesis**: Combining insights into actionable information

                ## Key Takeaways

                - The topic is multifaceted and requires careful consideration
                - Multiple perspectives have been incorporated
                - Recommendations are provided for next steps

                ## Conclusion

                This content has been crafted to meet the specified requirements while maintaining clarity and professionalism.

                ---
                *Content created by Writing Specialist*
            """).strip()
